server:
  port: 9002
  shutdown: graceful

spring:
  application:
    name: USER-SERVICE
  lifecycle:
    timeout-per-shutdown-phase: 20s

management:
  endpoint:
    health:
      probes:
        enabled: true